### ISSUE TITLE
Docs'u var mı?

### ISSUE THREAD

**Issue by yorunoken** [hakanatak/dataibbgovtr#14]
Kullanmak istiyorum da, "Service Unavailable" hatası veriyor.

**Comment by eoksum** [comment]
> Kullanmak istiyorum da, "Service Unavailable" hatası veriyor.

Bu API kaput maalesef hocam. Ben kendi API'mi yazdım, sizler de kullanabilirsiniz biraz daha kapsamlı oldu benimkisi
https://iett.emreoksum.com.tr

**Comment by yorunoken** [comment]
eyw kardeşim

**Comment by hakanatak** [comment]
Selamlar,
API olduğu gibi çalışıyor açıklama metni girmiştim oradan bakabilirsiniz. Bağlı olduğu API bakıma girdiği için bazen çalışmıyor olabilir. 

  örnek: https://mekansal.herokuapp.com/api/durak

**Comment by hakanatak** [comment]
@eoksum eline sağlık, api güzel olmuş fakat bu api *.geojson olarak mekansal veri dönüyor kullanım amaçları farklı kullanmak isteyenler için belirtmek istedim.

**Comment by yorunoken** [comment]
@eoksum Dostum haberin olsun KapiNo'nun DEMO'sundaki link `https://iett.emreoksum.com.tr/rest.php?Plaka=34ES2229`'e götürüyor, doğru link `https://iett.emreoksum.com.tr/rest.php?KapiNo=132C` olmalı.
