### ISSUE TITLE
APİ ÇÖKMESİ

### ISSUE THREAD

**Issue by mfurkanozgenc** [hakanatak/dataibbgovtr#16]
Merhaba hocam apiyi kullanıyorum ancak ara ara api çöküyor.Sebebi nedir ? 
![qqqqq](https://github.com/user-attachments/assets/9d543fd7-0358-400d-9fe6-ae3b11171886)

**Comment by hakanatak** [comment]
Merhaba, sayfayı incelediğimde 503 hatası olduğunu görüyorum. Uygulamayı
yeniden deploy ettim fakat düzelmedi. Serviste kesintiler yaşandığını ön
görüyorum. Uygulamada bir problem görünmüyor.

iyi çalışmalar dilerim,
Hakan Atak

**Comment by mfurkanozgenc** [comment]
Sorun İBB servis tarafında doğru mudur ?

**Comment by mfurkanozgenc** [comment]
Teşekkürler,İyi Çalışmalar...

**Comment by hakanatak** [comment]
Evet servis bazen calismiyor. Şu an veri geliyor.

26 Eyl 2024 Per 16:54 tarihinde Mustafa Furkan Özgenç <
***@***.***> şunu yazdı:

**Comment by mfurkanozgenc** [comment]
Hocam merhaba,
Rahatsız ediyorum kusura bakmayın.Duraktan hangi otobüs hatlarının geçtiğini alabileceğim bir yer var mıdır? Bulamadım sizin bilginiz var mı acaba ?
İyi Çalışmalar...

**Comment by hakanatak** [comment]
Data.ibb.gov.tr de İETT api dokümanı var ordan detayli verileri
bulabilirsiniz.

27 Eyl 2024 Cum 12:50 tarihinde Mustafa Furkan Özgenç <
***@***.***> şunu yazdı:

**Comment by mfurkanozgenc** [comment]
Hocam çok inceledim ancak .net core apiden bu verileri çekemiyorum.Bilginiz var mı bu konuda ?

**Comment by hakanatak** [comment]
Maalesef js ve python ile ilgili destek olabilirim.
